---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/reservations":
    get:
      summary: List all reservations for the user
      tags:
      - Reservation index
      description: Shows all the reservations for the current user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successfull_login:
                  value:
                    status: Success
                    message: signed in
                    data: "#<Reservation::ActiveRecord_Relation:0x000000010ce8f168>"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication_token:
                  type: string
              required:
              - authentication_token
  "/api/v1/vehicles/{vehicle_id}/reservations":
    post:
      summary: create reservation
      tags:
      - Reservation create
      description: Creates a new reservation
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successfull_create_reservation:
                  value:
                    status: Success
                    message: created reservation
                    data:
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                Failed_create_reservation:
                  value:
                    status: Failed
                    message: Failed to create a new reservation
                    data:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication_token:
                  type: string
                vehicle_id:
                  type: integer
                city:
                  type: string
                date:
                  type: string
              required:
              - authentication_token
              - city
              - date
  "/api/v1/users":
    get:
      summary: list all users
      tags:
      - Users index
      description: Shows all the users for the current user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successfull_login:
                  value:
                    status: Success
                    message: signed in
                    data: "#<User::ActiveRecord_Relation:0x000000010d8cc978>"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authentication_token:
                  type: string
              required:
              - authentication_token
  "/api/v1/vehicles":
    get:
      summary: list vehicles
      responses:
        '200':
          description: successful
    post:
      summary: create vehicle
      responses:
        '200':
          description: successful
  "/api/v1/vehicles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show vehicle
      responses:
        '200':
          description: successful
    patch:
      summary: update vehicle
      responses:
        '200':
          description: successful
    put:
      summary: update vehicle
      responses:
        '200':
          description: successful
    delete:
      summary: delete vehicle
      responses:
        '200':
          description: successful
  "/users/":
    post:
      summary: create user
      tags:
      - Sign-up
      description: Creates a new user
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successfull_signup:
                  value:
                    status: Success
                    message: created users
                    data: "#<User:0x000000010e294988>"
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                Failed_SignUp:
                  value:
                    status: 500
                    message: Registration failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                name:
                  type: string
                roles:
                  type: array
              required:
              - email
              - password
              - password_confirmation
              - name
              - roles
  "/users/sign_in":
    post:
      summary: create session
      tags:
      - Sign-in
      description: Authenticates an user and returns an authetication token
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                successfull_login:
                  value:
                    status: Success
                    message: signed in
                    data: "#<User:0x000000010e2cd3c8>"
        '401':
          description: unauthorized
          content:
            application/json:
              examples:
                invalid_credentials:
                  value:
                    status: failed
                    message: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
