---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
  "/api/v1/vehicles/{vehicle_id}/reservations":
    parameters:
    - name: vehicle_id
      in: path
      description: vehicle_id
      required: true
      schema:
        type: string
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/vehicles/{vehicle_id}/reservations/{id}":
    parameters:
    - name: vehicle_id
      in: path
      description: vehicle_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
  "/api/v1/vehicles":
    get:
      summary: list vehicles
      responses:
        '200':
          description: successful
    post:
      summary: create vehicle
      responses:
        '200':
          description: successful
  "/api/v1/vehicles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show vehicle
      responses:
        '200':
          description: successful
    patch:
      summary: update vehicle
      responses:
        '200':
          description: successful
    put:
      summary: update vehicle
      responses:
        '200':
          description: successful
    delete:
      summary: delete vehicle
      responses:
        '200':
          description: successful
  "/users/cancel":
    get:
      summary: cancel registration
      responses:
        '200':
          description: successful
  "/users/sign_up":
    get:
      summary: new registration
      responses:
        '200':
          description: successful
  "/users/edit":
    get:
      summary: edit registration
      responses:
        '200':
          description: successful
  "/users":
    patch:
      summary: update registration
      responses:
        '200':
          description: successful
    put:
      summary: update registration
      responses:
        '200':
          description: successful
    delete:
      summary: delete registration
      responses:
        '200':
          description: successful
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/users/sign_in":
    get:
      summary: new session
      responses:
        '200':
          description: successful
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/users/sign_out":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
